### ISSUE TITLE
Autoconf fails

### ISSUE THREAD

**Issue by W0FNQ** [libyal/libvhdi#1]
I am getting this error with UBUNTU 64-bit -- 3.13.0-49-lowlatency.  Libtool is:
libtool (GNU libtool) 2.4.2

     configure.ac:22: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

configure.ac:31: error: possibly undefined macro: AC_PROG_LIBTOOL

autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by joachimmetz** [comment]
I'll have a look if time permits, I opt using the prepackaged version for the time being.

**Comment by W0FNQ** [comment]
Thanks — The tar.gz alpha file worked — couldn’t get autogen to work.

**Comment by joachimmetz** [comment]
Try installing libtool:
```
sudo apt-get install libtool
```
