### ISSUE TITLE
Mention that disk size is stored in big-endian?

### ISSUE THREAD

**Issue by nixomose** [libyal/libvhdi#10]
it might be worth mentioning that the 

field:
Disk sizeContains the size of the disk in bytes
--
is stored in big endian format. I would have expected it to be little endian given ms file formats.

**Comment by joachimmetz** [comment]
Isn't this already mention in https://github.com/libyal/libvhdi/blob/master/documentation/Virtual%20Hard%20Disk%20(VHD)%20image%20format.asciidoc#1-overview ?

**Comment by joachimmetz** [comment]
>  I would have expected it to be little endian given ms file formats.

If I'm not mistaken Microsoft acquired the company that initially created this format.

**Comment by nixomose** [comment]
ahhh, whoops. missed that line.
Sorry about that.
thanks.
