### ISSUE TITLE
Support for 4KB sectors / Method to determine sector size?

### ISSUE THREAD

**Issue by datasynergyuk** [libyal/libvhdi#11]
The current implementation does not appear to provide a method to determine the sector size. 

This could be called libvhdi_handle_get_bytes_per_sector()

**Comment by datasynergyuk** [comment]
Maybe this is because VHD only support 512 byte sectors and because Libvhdi doesn't yet support VHDX?

**Comment by joachimmetz** [comment]
Libvhdi does not support vhdx as indicated in https://github.com/libyal/libvhdi/issues/4. Also you likely want to determine/confirm the sector size based on the actual content not on the metadata.

**Comment by joachimmetz** [comment]
Closing issue questioned answered, no follow up from reporter.
