### ISSUE TITLE
PAYLOAD_BLOCK_NOT_PRESENT block state for differential VDHX image not handled the same as by Windows implementation

### ISSUE THREAD

**Issue by devmd5** [libyal/libvhdi#17]
Thank you for the fantastic VHD library. 

I have been experimenting with the new VHDX support. However, I found that libvhdi_file_read_buffer_at_offset() will sometimes return unexpected data. This data appears to be the original file header and is repeated at intervals throughout data.

I have uploaded an a small example VHDX file. This contains a minimal NTFS file system and is available here:

https://drive.google.com/file/d/1ARTrgObHAlfEtWIDC7yguuRpKRQMRTNV

When I open this file usingLibvhdi, I found that the signature "vhdxfile" is present at the following offsets: 0x2000000, 0x4000000, 0x6000000, 0x8000000 etc. This data is not present when the file is mounted using the built-in Windows VHDX feature.

**Comment by joachimmetz** [comment]
thx for the report I'll have a look when time permits

**Comment by joachimmetz** [comment]
Can you indicate how this image was created?

It's physical sector size is 512 and logical sector size is 4096 but neither PowerShell New-VHD or diskpart appear to support this configuration.

**Comment by joachimmetz** [comment]
Made some changes in https://github.com/libyal/libvhdi/commit/df726ac06bbb6f576347b6da461e4700fab4737f to fill payload blocks with state PAYLOAD_BLOCK_NOT_PRESENT with 0-byte values.

**Comment by devmd5** [comment]
The VHDX file was created using the Windows GUI. No special tool was used:

1. Open Disk Management
2. Create VHD
3. Enter file name: D:\1GB.vhdx
4. Select VHDX format
5. Select size: 1GB
6. Select "Dynamically Expanding"
7. Click OK

I think the revised title for this issue may be wrong. This VHDX file was not expected to be unusual in any way and Windows reports it has a logical sector size of 512 bytes (not 4096 as you suggested):

C:\> fsutil fsinfo ntfsinfo g:

NTFS Volume Serial Number :        0xf8a4ff98a4ff5818
NTFS Version      :                3.1
LFS Version       :                2.0
Total Sectors     :                2,091,007  (1021.0 MB)
Total Clusters    :                  261,375  (1021.0 MB)
Free Clusters     :                  258,661  (1010.4 MB)
Total Reserved Clusters :              1,024  (   4.0 MB)
Reserved For Storage Reserve :             0  (   0.0 KB)
Bytes Per Sector  :                512
Bytes Per Physical Sector :        4096
Bytes Per Cluster :                4096
Bytes Per FileRecord Segment    :  1024
Clusters Per FileRecord Segment :  0
Mft Valid Data Length :            256.00 KB
Mft Start Lcn  :                   0x0000000000015455
Mft2 Start Lcn :                   0x0000000000000002
Mft Zone Start :                   0x0000000000015480
Mft Zone End   :                   0x000000000001d400
MFT Zone Size  :                   127.50 MB
Max Device Trim Extent Count :     4096
Max Device Trim Byte Count :       0xffffffff
Max Volume Trim Extent Count :     62
Max Volume Trim Byte Count :       0x40000000
Resource Manager Identifier :      184E7AEB-2D9A-11EB-956D-D45D64275693

**Comment by joachimmetz** [comment]
> The VHDX file was created using the Windows GUI. No special tool was used:

Interesting

> This VHDX file was not expected to be unusual in any way and Windows reports it has a logical sector size of 512 bytes (not 4096 as you suggested):

from the VHDX data, note that this is not the same as sector size of the file system

```
libvhdi_metadata_values_read_item_file_io_handle: reading metadata item at offset: 2162704 (0x00210010).
libvhdi_metadata_values_read_item_data: metadata item identifier        : 8141bf1d-a96f-4709-ba47-f233a8faab5f
libvhdi_metadata_values_read_item_data: metadata item description       : Logical sector size
libvhdi_metadata_values_read_item_data: metadata item data:
00000000: 00 02 00 00                                        ....

libvhdi_metadata_values_read_item_data: logical sector size             : 512

libvhdi_metadata_values_read_item_file_io_handle: reading metadata item at offset: 2162708 (0x00210014).
libvhdi_metadata_values_read_item_data: metadata item identifier        : cda348c7-445d-4471-9cc9-e9885251c556
libvhdi_metadata_values_read_item_data: metadata item description       : Physical sector size
libvhdi_metadata_values_read_item_data: metadata item data:
00000000: 00 10 00 00                                        ....

libvhdi_metadata_values_read_item_data: physical sector size            : 4096
```

> I think the revised title for this issue may be wrong.

Could be, I'll change it, the crux of the issue seems to be that certain block states are not yet correctly handled.

**Comment by joachimmetz** [comment]
Have a look at https://github.com/libyal/libvhdi/commit/f6841269e7ab1581a2ae2d1290638a68750acab4 see if that solves the issue for you

**Comment by devmd5** [comment]
Wow. Thank you. I will try again.

Incidentally, I found you can use the following Powershell command to change physical sector size: 

set-vhd VHDname.vhdx –PhysicalSectorSizeBytes 4096

This may be useful to someone else.

**Comment by joachimmetz** [comment]
Thx I use that command in https://github.com/dfirlabs/vhdx-specimens/blob/main/generate-speciments-windows.ps1 but for some reason it does not allow me to combine ` -PhysicalSectorSizeBytes 512  -LogicalSectorSizeBytes 4096`

**Comment by devmd5** [comment]
Thank you. I did some more testing.

The problem is now a lot better but there remains a similar issue (possibly on a smaller scale). To illustrate this, I created a 40GB VHDX file using the Windows interface as before. You can download this here:

[https://drive.google.com/file/d/1cb4whKrypN5SK21rkuo0YUg1F-DZ8pKp]

Superficially, Libvhdi works okay. However, at sector 83881983 (offset 0x9ffdffe00) it is different. In the original VHDX file there is a copy of the NTFS metadata. However, this is not present when accessed via Libvhdi. 

There may be more differences than this but this one is easy to demonstrate with a tiny VHDX file.

**Comment by joachimmetz** [comment]
That appears to be a different issue. Can you give https://github.com/libyal/libvhdi/commit/a5188619b62d6504c622142889f6facb512b0632 a try.

**Comment by devmd5** [comment]
Thank you. That works fine now.

**Comment by joachimmetz** [comment]
thx for confirming. I'll build a new pre-release once CI testing has completed.

**Comment by joachimmetz** [comment]
pushed new pre-release, closing
