### ISSUE TITLE
Question: writing disks

### ISSUE THREAD

**Issue by rvanlaar** [libyal/libvhdi#18]
Looking at the man page for libvhdi I only see read operations.
Is it possible to create and write to vhd disks with this library?

**Comment by joachimmetz** [comment]
nope this library focuses on read only. If you want to write VDI for compatibility reasons have a look at the fixed format, it is basically a footer after a raw storage media image.

**Comment by rvanlaar** [comment]
Thank you for the info. Looking at your documentation, it seems doable to create the 
footer. The sparse ones also look interesting. 

I started looking at VHD because it's listed as supported by BasiliskII. A classic mac emulator. The ability to create snapshots seemed nice. As it turns out, this was only supported via the blktap from xen tools. Which has seen been deprecated.

However as I'm searching further info on it seems like this format has come in disuse. For example Xen tools to manage them are no longer there. 

Do you have any advice on which disk formats do have snapshot support on Linux?

**Comment by joachimmetz** [comment]
> Do you have any advice on which disk formats do have snapshot support on Linux?

QCOW as a format has snapshot support.

**Comment by joachimmetz** [comment]
No updates, closing issue
