### ISSUE TITLE
Mounting Differencing VHDX Files

### ISSUE THREAD

**Issue by arijitAD** [libyal/libvhdi#4]
How do we mount multiple VHDX differencing file in a single mount point ?
file1.vhdx , file2.avhdx, file3.avhdx

**Comment by joachimmetz** [comment]
VHDX is not supported, if you can provide me with sample files I could have look how much the format differs from VHDI

**Comment by arijitAD** [comment]
You can check VHDX specification here.
https://www.microsoft.com/en-us/download/confirmation.aspx?id=34750

**Comment by arijitAD** [comment]
Also, can you give me an example for mounting differencing VHD disk. Suppose if there are two differencing VHD disk. One parent and One child. How do i mount both of them to a single mount point ?

**Comment by joachimmetz** [comment]
Just point vhdimount to the most recent diff image you want to mount. Make sure it can find its parent images.

**Comment by joachimmetz** [comment]
> You can check VHDX specification here.

Thanks, however this means I have to make my own test images and with my limited available time means this will be a low priority.

**Comment by arijitAD** [comment]
I am trying to built a similar library for mounting vhdx files. Can you tell me how you combine multiple differencing vhd files and provide a single merged view of that file using FUSE driver ?
It will be really helpful if you can point to that part of code or share some resource which i can read and get understanding of it.

**Comment by joachimmetz** [comment]
@arijitAD, I'm not sure what you are asking me

fuse is handled here:
https://github.com/libyal/libvhdi/blob/master/vhditools/vhdimount.c
https://github.com/libyal/libvhdi/blob/master/vhditools/mount_handle.c

Dealing with differential images is done by the library.

**Comment by joachimmetz** [comment]
Closing issue, question answered
