### ISSUE TITLE
Building from HEAD failing

### ISSUE THREAD

**Issue by rishwanth1995** [libyal/libvhdi#6]
I am trying to build libvhdi from source. But the build is failing due to some cppflags missing in libcerror. This happens only after https://github.com/libyal/libcerror/commit/2066b60af1cfc51b9e8161461168cf81427b3561 commit in libcerror.

![image](https://user-images.githubusercontent.com/26807771/44058069-f44d7ac2-9f1a-11e8-88c7-5c0c23de79fb.png).

Can you take a look into this issue?. or am I doing something wrong?

My commands to build from source:

`./synclibs.sh `
`./autogen.sh `
`./configure `
`make`

**Comment by joachimmetz** [comment]
This is a known issue. git HEAD is always work in progress and only recommended as the version to use if you are actively developing libvhdi. Also see: https://github.com/libyal/libvhdi/wiki/Building#read-first

This issue will be addressed with the next commit.

**Comment by joachimmetz** [comment]
Should be fixed now, closing issue.
